### ISSUE TITLE
Fix all plugins failing to load if Newtonsoft.Json is missing

### ISSUE THREAD

**Issue by isolno** [risk-of-thunder/BepInEx#4]
https://github.com/risk-of-thunder/BepInEx/blob/de944e4a41b1208ea8d94305aa3a5ff2eeb844e8/BepInEx/Bootstrap/Chainloader.cs#L440
This call will throw if Newtonsoft.Json is missing, preventing all plugins from being loaded. As this prevents BepInEx from functioning without dependancies, this should be either fixed, or have Newtonsoft.Json included in core instead of a seperate mod.

**Comment by KingEnderBrine** [comment]
This is a repo for Risk of Rain 2 specifically. A separate mod, which is RoR2BepInEx pack, is a requirement and installed by everyone (unless you do it manually and miss dependencies for BepInEx). So it always works and doesn't need a fix.

**Comment by KingEnderBrine** [comment]
The reason why Newtonsoft wasn't included in the first place was because RoR was shipping with a copy of Newtonsoft at the time this change was added. But it was removed with second DLC, and it's better to not update BepInEx itself unless there is a very good reason and no other way to do it, so it was added to RoR2BepInExPack instead.

**Comment by isolno** [comment]
This is an issue specific to the ror2 fork, as this call doesnt exist in the original. While Newtonsoft does exist in the RoR2BepInEx pack, I believe that the loading of plugins shouldnt require another mod to be installed. Especialy since the fix is really simple.
